import { League_Spartan, Alice } from 'next/font/google'
import "./globals.css";
import GoogleProvider from '@/providers/GoogleProvider';
import ReduxProvider from '@/providers/ReduxProvider';
import ClientLayout from '@/component/ClientLayout';


const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-league-spartan',
})

const alice = Alice({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-alice',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.variable} ${alice.variable} antialiased`}>
      <GoogleProvider>
      <ReduxProvider>
        <div className='relative'>
           <ClientLayout>
              {children}
            </ClientLayout>
        </div>
        </ReduxProvider>
        </GoogleProvider>
      </body>
    </html>
  );
}
