import { League_Spartan, Alice } from 'next/font/google'
import "./globals.css";
import GoogleProvider from '@/providers/GoogleProvider';
import ReduxProvider from '@/providers/ReduxProvider';
import ClientLayout from '@/component/ClientLayout';


const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-league-spartan',
})

const alice = Alice({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-alice',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

				<meta
					property="og:url"
					content="https://staging.mydivinestays.com/"
				/>
				<meta
					property="og:image"
					content="/favicon.svg"
				/>


				<link rel="shortcut icon" href="/favicon.svg" />
				<link rel="icon" type="image/x-icon" href="/favicon.svg" />
				<link rel="icon" type="image/png" sizes="48x48" href="/favicon.svg" />
				<link rel="icon" type="image/png" sizes="40x40" href="/favicon.svg" />
				<meta
					name="viewport"
					content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
			/>
				{/* <title>
					SCT Website
				</title> */}
			</head>
      <body className={`${leagueSpartan.variable} ${alice.variable} antialiased`}>
      <GoogleProvider>
      <ReduxProvider>
        <div className='relative'>
           <ClientLayout>
              {children}
            </ClientLayout>
        </div>
        </ReduxProvider>
        </GoogleProvider>
      </body>
    </html>
  );
}
